# -*- mode: ruby -*-
# vi: set ft=ruby :
#

require 'erb'

$vg_role = ENV['VG_ROLE']                         || "straycat::roles::base"
$vg_profile = ENV['VG_PROFILE']                   || ''
$inst_home = ENV['VG_INST_HOME']                  || File.dirname(__FILE__)
$inst_name = ENV['VG_INST_NAME']                  || $inst_home.split(File::SEPARATOR)[-1]
$hostname = ENV['VG_HOSTNAME']                    || "%s.straycat.local" % $inst_name
$puppet_clone = ENV['VG_PUPPET_CLONE']            || $inst_home.split(File::SEPARATOR)[0..-2].join(File::SEPARATOR)
$ssh_private_key = ENV['VG_SSH_PRIVATE_KEY']      || "%s/vagrant/straycat_vagrant_rsa" % $puppet_clone
$vg_puppetmaster_dir = ENV['VG_PUPPETMASTER_DIR'] || "/etc/puppetmaster"
$facter_vars = ENV['VG_FACTER_VARS']              || '' # "key1=val1;key2=val2a,val2b;key3=val3"
$vg_gui = ENV['VG_GUI']                           || false
$inst_vols = ENV['VG_INST_VOLS']                  || '1'
$ebs_vols = ENV['VG_EBS_VOLS']                    || '0'
$debug = ENV['DEBUG']                             || false
$cpu = ENV['VG_CPU']                              || '1'
$ram = ENV['VG_RAM']                              || '1024'

$vm_box =  ENV['VG_VM_BOX']                       || 'CentOS-6.6-x86_64-20150110134049'
$vm_box_site = ENV['VG_VM_BOX_SITE']              || 'https://s3.amazonaws.com/straycat.dhs.org/os-images/vagrant'

$aws_access_key = ENV['AWS_ACCESS_KEY']
$aws_secret_key = ENV['AWS_SECRET_KEY']
$aws_keypair_name = 'straycat'
$aws_region = 'us-east-1'
$aws_ami = 'ami-3270035a'
$aws_user = 'vagrant'
$aws_authorized_key = "#{ENV['HOME']}/.ssh/id_rsa.pub"
$aws_private_key = "#{ENV['HOME']}/.ssh/id_rsa"
$aws_user_data_file = "#{$inst_home}/../../aws_box/user_data.txt.erb"

if ENV['VAGRANT_DEFAULT_PROVIDER']
  abort "Must set $AWS_ACCESS_KEY in environment." unless ENV['AWS_ACCESS_KEY']
  abort "Must set $AWS_SECRET_KEY in environment." unless ENV['AWS_SECRET_KEY']
  abort "Missing SSH public key #{$aws_authorized_key}" unless File.exist?($aws_authorized_key)
  abort "Missing SSH private key #{$aws_authorized_key}" unless File.exist?($aws_private_key)
end

# Toggle local hostname setup from CLI.
#
# FIXME: Really need tyo get resolution working with dhcp setups.  Should
# look at the following ideas.
# * https://github.com/smdahlen/vagrant-hostmanager/issues/63
# * https://github.com/smdahlen/vagrant-hostmanager/issues/121
if ENV['VG_HM_LOCAL'] =~ /(1|true)/
  $hosmanager_manage_host = true
else
  $hosmanager_manage_host = false
end

# Default puppet versions. Override from profiles if needed.
$puppet_ver          = '3.7.3-1.el6'
$facter_ver          = '2.3.0-1.el6'
$hiera_ver           = '1.3.4-1.el6'
$hiera_eyaml_ver     = '2.0.6'
$hiera_eyaml_gpg_ver = '0.4'

# Used for minor differences when provisioning local pupeptmaster.
$centos_major = '6'

# Enable Puppet debugging
if $debug != false
  debug_flag = '--debug'
else
  debug_flag = ''
end

USER = ENV['USER']
VG_PUPPETMASTER_LOCAL = '/etc/puppet-local'
PUPPET_MANIFEST_PATH = ["vm", "#{VG_PUPPETMASTER_LOCAL}/vagrant/manifests"]

unless system('which r10k > /dev/null')
  abort "r10k not available."
end

# Load our profiles so we get any variables defined in them
$vg_profile.split(',').each do |p|
  load "#{p}/vars.rb" if File.exists?("#{p}/vars.rb")
end

# Changes in namied provisioners
Vagrant.require_version ">= 1.7.1"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = $vm_box

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "#{$vm_box_site}/#{$vm_box}.box"

  # Hostname of new instance.
  config.vm.hostname = $hostname

  # Location of insecure private key.
  config.ssh.private_key_path = $ssh_private_key

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  # vagrant-hostmanager setup.  We have to circumvent /etc/hosts handling
  # from puppet for this to work.
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = $hosmanager_manage_host


  ### Providers
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.

  ## Virtualbox
  config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true

    # Enable GUI if VG_GUI is set in env.
    if $vg_gui != false
      vb.gui = true
    end

    # Add an additional proc.
    vb.customize ["modifyvm", :id, "--cpus", "#{$cpu}"]

    # Ensure virtio because Vagrant has issues munging other types of NICs
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']

    # Disable USB 2.0 which requires the VBox extensions pack.
    vb.customize ["modifyvm", :id, "--usbehci", "off"]

   # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "#{$ram}"]

    # Was required to get more support for more disk volumes.
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]

    # Ephemeral vols
    if $inst_vols.to_i > 0
      (1..$inst_vols.to_i).each do |n|
        disk_path = "#{$inst_home}/data-0-#{n}-#{rand(36**12).to_s(36)}.vdi"
        vb.customize ["createhd", "--filename", disk_path, "--size", "4096"]
        vb.customize ["storageattach", :id,  "--storagectl", "SATA Controller", "--port", n, "--device", 0,  "--type", "hdd", "--medium", disk_path]
      end
    end

    # Faux-EBS vols
    if $ebs_vols.to_i > 0
      vb.customize ["storagectl", :id, "--add", "sata", "--name", "SATA-1", "--portcount", $ebs_vols.to_i]
      (1..$ebs_vols.to_i).each do |n|
        disk_path = "#{$inst_home}/data-1-#{n}-#{rand(36**12).to_s(36)}.vdi"
        vb.customize ["createhd", "--filename", disk_path, "--size", "4096"]
        vb.customize ["storageattach", :id,  "--storagectl", "SATA-1", "--port", n, "--device", 0,  "--type", "hdd", "--medium", disk_path]
      end
    end
  end


  ## AWS
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = $aws_access_key
    aws.secret_access_key = $aws_secret_key
    aws.keypair_name = $aws_keypair_name
    aws.ami = $aws_ami

    override.ssh.username = $aws_user
    override.ssh.private_key_path = $aws_private_key

    override.vm.box = "#{$vm_box}-aws"
    override.vm.box_url = "#{$inst_home}/../../aws_box/#{$vm_box}-aws.box"

    # See below for ideas on using aws.user_data
    # https://github.com/mitchellh/vagrant/issues/1482

    $aws_authorized_key_data = File.read($aws_authorized_key)

    # File.read() is run everytime but user_data_file path is not correct
    # until the instance is created.
    aws.user_data = ERB.new(File.read($aws_user_data_file)).result if File.exists?($aws_user_data_file)
  end

  ## Provisioners
  #
  # Prevent breakage caused by updating the package during a run.
  config.vm.provision :shell do |shell|
    shell.inline = "yum -y install puppet-#{$puppet_ver} facter-#{$facter_ver}"
  end

  # Share local Puppet tree to host.
  config.vm.synced_folder $puppet_clone, "/etc/puppet-local", owner: "root", group: "root"

  # Provision Puppet master inside host that will serve up local Puppet
  # tree.  A separate provisioner will handle talking to this Puppet master.
  config.vm.provision 'default_puppet', type: 'puppet' do |puppet|

    puppet.facter = {
      "sc_environment"         => "qa",
      "environment"            => "production",
      "data_center"            => "local",
      "sc_puppetmaster_server" => "localhost",
      "os"                     => "centos6",
      "provider"               => "virtualbox",
      "security_group"         => "default",
      "vg_puppetmaster_dir"    => $vg_puppetmaster_dir,
      "vg_puppetmaster_local"  => VG_PUPPETMASTER_LOCAL,
      "default_role"           => $vg_role,
      "creator"                => USER,
      "description"            => "Test server for role " + $vg_role,
      "puppet_ver"             => $puppet_ver,
      "hiera_ver"              => $hiera_ver,
      "hiera_eyaml_ver"        => $hiera_eyaml_ver,
      "hiera_eyaml_gpg_ver"    => $hiera_eyaml_gpg_ver,
      "centos_major"           => $centos_major
    }

    if defined? $facter_vars
      facter_extra = $facter_vars
      puppet.facter['facter_extra'] = facter_extra
    end

    puppet.manifests_path = PUPPET_MANIFEST_PATH
    puppet.manifest_file  = "puppetmaster.pp"
    puppet.options        = "--templatedir #{VG_PUPPETMASTER_LOCAL}/vagrant/templates #{debug_flag}"
  end

  # Run Puppet against local Puppet master.
  config.vm.provision 'default_puppet_server', type: 'puppet_server' do |puppet|
    puppet.puppet_server = "localhost"
    puppet.options       = "--verbose --waitforcert 1 #{debug_flag}"
  end
end

# Load our profiles so we override any configuration in the previous
# configure block.
$vg_profile.split(',').each do |p|
  load "#{p}/config.rb" if File.exists?("#{p}/config.rb")
end
