---
straycat::infra::git:             git.straycat.lan

straycat::infra::ipa::adminpw:    InsecureAdminPW
straycat::infra::ipa::domain:     straycat.local
straycat::infra::ipa::dspw:       InsecureDataStorePw
straycat::infra::ipa::join_user:  ipa-join-user
straycat::infra::ipa::join_pass:  InsecureJoinUser
straycat::infra::ipa::master:     ipa-master.straycat.local
straycat::infra::ipa::otp:        InsecureOTP
straycat::infra::ipa::realm:      STRAYCAT.LOCAL
straycat::infra::ipa::replica1:   ipa-slave-1.straycat.local
straycat::infra::ipa::replica2:   ipa-slave-2.straycat.local

straycat::infra::ldap1: "%{hiera('straycat::infra::ipa::master')}"
#straycat::infra::ldap2: "%{hiera('straycat::infra::ipa::replica1')}"

straycat::infra::pgsql::host:     pgsql.straycat.local
straycat::infra::pgsql::port:     5432

straycat::infra::puppet::db:      puppetdb.straycat.local
straycat::infra::puppet::foreman: foreman.straycat.local
straycat::infra::puppet::master:  localhost

straycat::infra::ntp::server1:    us.pool.ntp.org


straycat::os::ipa_setup:                  false
straycat::os::ipa_client::ipa_domain:     "%{hiera('straycat::infra::ipa::domain')}"
straycat::os::ipa_client::ipa_join_user:  "%{hiera('straycat::infra::ipa::join_user')}"
straycat::os::ipa_client::ipa_join_pass:  "%{hiera('straycat::infra::ipa::join_pass')}"
straycat::os::ipa_client::ipa_otp:        "%{hiera('straycat::infra::ipa::otp')}"
straycat::os::ipa_client::ipa_realm:      "%{hiera('straycat::infra::ipa::realm')}"
straycat::os::ipa_client::ipa_server:     "%{hiera('straycat::infra::ipa::master')}"

straycat::os::puppet::puppet_server:  "%{hiera('straycat::infra::puppet::master')}"

straycat::os::resolv::domainname: "%{::domain}"

straycat::os::time::ntp_servers:
  - "%{hiera('straycat::infra::ntp::server1')}"


straycat::svc::cassandra::cluster_name:                 'localTest'

straycat::svc::puppet::foreman::foreman_admin_username: admin
straycat::svc::puppet::foreman::foreman_admin_password: changeme
straycat::svc::puppet::foreman::foreman_db_host:        "%{hiera('straycat::infra::pgsql::host')}"
straycat::svc::puppet::foreman::foreman_db_username:    foreman
straycat::svc::puppet::foreman::foreman_db_password:    MyWeakPassword

straycat::svc::ipa::master::ipa_adminpw:  "%{hiera('straycat::infra::ipa::adminpw')}"
straycat::svc::ipa::master::ipa_domain:   "%{hiera('straycat::infra::ipa::domain')}"
straycat::svc::ipa::master::ipa_dspw:     "%{hiera('straycat::infra::ipa::dspw')}"
straycat::svc::ipa::master::ipa_forwarders:
  - "%{hiera('straycat::infra::dns::forwarder1')}"
  - "%{hiera('straycat::infra::dns::forwarder2')}"
straycat::svc::ipa::master::ipa_realm:    "%{hiera('straycat::infra::ipa::realm')}"

straycat::svc::phppgadmin::pgsql_db_host: "%{hiera('straycat::infra::pgsql::host')}"

straycat::svc::puppet::foreman_proxy::foreman_host: "%{hiera('straycat::infra::puppet::foreman')}"

# This should be a lookup for the puppetmaster except in a Vagrant env.
straycat::svc::puppet::master::puppet_ca_allow: 'puppetmaster.straycat.local'
