---
#straycat::infra::dns:
#  - ipa-master.straycat.local

straycat::infra::git:             git.straycat.lan

straycat::infra::ipa::adminpw:    InsecureAdminPW
straycat::infra::ipa::domain:     straycat.local
straycat::infra::ipa::dspw:       InsecureDataStorePw
straycat::infra::ipa::join_user:  ipa-join-user
straycat::infra::ipa::join_pass:  InsureJoinUser
straycat::infra::ipa::master:     ipa-master.straycat.local
straycat::infra::ipa::realm:      STRAYCAT.LOCAL
straycat::infra::ipa::replica:
  - ipa-slave-1.straycat.local
  - ipa-slave-2.straycat.local

straycat::infra::ldap: "%{hiera('straycat::infra::ipa::master')}"
# We don't have any replicas but if we did we'd probably use them.
#  - ipa-slave-1.straycat.local
#  - ipa-slave-2.straycat.local

straycat::infra::pgsql:           pgsql.straycat.local

straycat::infra::puppet::db:      puppetdb.straycat.local
straycat::infra::puppet::foreman: foreman.straycat.local
straycat::infra::puppet::master:  localhost
straycat::infra::time:
  - us.pool.ntp.org

straycat::os::resolv::domainname: "%{::domain}"
