---
straycat::infra::git:             git.straycat.lan

straycat::infra::ipa::adminpw:    InsecureAdminPW
straycat::infra::ipa::domain:     straycat.local
straycat::infra::ipa::dspw:       InsecureDataStorePw
straycat::infra::ipa::join_user:  ipa-join-user
straycat::infra::ipa::join_pass:  InsureJoinUser
straycat::infra::ipa::master:     ipa-master.straycat.local
straycat::infra::ipa::realm:      STRAYCAT.LOCAL
straycat::infra::ipa::replica1:   ipa-slave-1.straycat.local
straycat::infra::ipa::replica2:   ipa-slave-2.straycat.local

straycat::infra::ldap1: "%{hiera('straycat::infra::ipa::master')}"
#straycat::infra::ldap2: "%{hiera('straycat::infra::ipa::replica1')}"

straycat::infra::pgsql:           pgsql.straycat.local

straycat::infra::puppet::db:      puppetdb.straycat.local
straycat::infra::puppet::foreman: foreman.straycat.local
straycat::infra::puppet::master:  localhost

straycat::infra::ntp::server1:    us.pool.ntp.org


straycat::os::ipa_setup:                  false
straycat::os::ipa_client::ipa_domain:     "%{hiera('straycat::infra::ipa::domain')}"
straycat::os::ipa_client::ipa_join_user:  "%{hiera('straycat::infra::ipa::join_user')}"
straycat::os::ipa_client::ipa_join_pass:  "%{hiera('straycat::infra::ipa::join_pass')}"
straycat::os::ipa_client::ipa_realm:      "%{hiera('straycat::infra::ipa::server')}"
straycat::os::ipa_client::ipa_server:     "%{hiera('straycat::infra::ipa::master')}"

straycat::os::puppet::puppet_server:  "%{hiera('straycat::infra::puppet::master')}"

straycat::os::resolv::domainname: "%{::domain}"

straycat::os::time::ntp_servers:
  - "%{hiera('straycat::infra::ntp::server1')}"
